import SHORT_GAME_TEST_1 from './SHORT_GAME/SHORT_GAME_TEST_1.png';
import SHORT_GAME_TEST_2 from './SHORT_GAME/SHORT_GAME_TEST_2.png';
import SHORT_GAME_TEST_3 from './SHORT_GAME/SHORT_GAME_TEST_3.png';
import SHORT_GAME_TEST_4 from './SHORT_GAME/SHORT_GAME_TEST_4.png';
import SHORT_GAME_TEST_5 from './SHORT_GAME/SHORT_GAME_TEST_5.png';
import SHORT_GAME_TEST_6 from './SHORT_GAME/SHORT_GAME_TEST_6.png';
import SHORT_GAME_TEST_7 from './SHORT_GAME/SHORT_GAME_TEST_7.png';
import SHORT_GAME_TEST_8 from './SHORT_GAME/SHORT_GAME_TEST_8.png';
import PUTTING_TEST_1 from './PUTTING/PUTTING_TEST_1.png';
import PUTTING_TEST_2 from './PUTTING/PUTTING_TEST_2.png';
import PUTTING_TEST_3 from './PUTTING/PUTTING_TEST_3.png';
import PUTTING_TEST_4 from './PUTTING/PUTTING_TEST_4.png';
import PUTTING_TEST_5 from './PUTTING/PUTTING_TEST_5.png';
import PUTTING_TEST_6 from './PUTTING/PUTTING_TEST_6.png';

export {
  SHORT_GAME_TEST_1,
  SHORT_GAME_TEST_2,
  SHORT_GAME_TEST_3,
  SHORT_GAME_TEST_4,
  SHORT_GAME_TEST_5,
  SHORT_GAME_TEST_6,
  SHORT_GAME_TEST_7,
  SHORT_GAME_TEST_8,
  PUTTING_TEST_1,
  PUTTING_TEST_2,
  PUTTING_TEST_3,
  PUTTING_TEST_4,
  PUTTING_TEST_5,
  PUTTING_TEST_6,
}